---
- name: Create temp dir
  become: yes
  file:
    path: /etc/temp
    state: directory

- name: Copy logstash package to system
  become: yes
  copy:
    src: logstash-7.17.1.tar.gz
    dest: /etc/temp/logstash.tar.gz

- name: Unpack logstash package
  become: yes
  unarchive:
    src: /etc/temp/logstash.tar.gz
    dest: /etc/temp/
    remote_src: true

- name: move unpacked package
  become: yes
  command: mv /etc/temp/logstash-7.17.1 /etc/logstash

- name: Create conf.d
  become: yes
  file:
    path: /etc/logstash/conf.d
    state: directory

- name: Add conf files
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    mode: 0700
  with_items:
    - 01-input.conf
    - 98-merge.conf

- name: Add conf templates
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 99-output.conf.j2, dest: /etc/logstash/conf.d/99-output.conf, mode: 0700 }
    - { src: 02-SampleFilter.conf.j2, dest: /etc/logstash/conf.d/02-SampleFilter.conf, mode: 0700 }
    - { src: logstash.service.j2, dest: /etc/systemd/system/logstash.service, mode: 0700 }
    - { src: startup.options.j2, dest: /etc/logstash/config/startup.options, mode: 0700 }
    