---
- name: Create temp dir
  become: yes
  file:
    path: /etc/temp
    state: directory

- name: Copy logstash package to system
  become: yes
  copy:
    src: logstash-7.17.1.tar.gz
    dest: /etc/temp/logstash.tar.gz

- name: Unpack logstash package
  become: yes
  unarchive:
    src: /etc/temp/logstash.tar.gz
    dest: /etc/temp/
    remote_src: true

- name: move unpacked package
  become: yes
  command: mv /etc/temp/logstash-7.17.1 /etc/logstash

- name: Create dirs
  become: yes
  file:
    path: /etc/logstash/"{{ item }}"
    state: directory
  with_items:
    - conf.d
    - logs

- name: Add conf files
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
  with_items:
    - 01-input.conf
    - 98-merge.conf

- name: Add conf templates
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 99-output.conf.j2, dest: /etc/logstash/conf.d/99-output.conf}
    - { src: 02-SampleFilter.conf.j2, dest: /etc/logstash/conf.d/02-SampleFilter.conf 
    - { src: logstash.service.j2, dest: /etc/systemd/system/logstash.service}
    - { src: startup.options.j2, dest: /etc/logstash/config/startup.options}

- name: Give correct permissions to logstash dir
  become: yes
  command: chmod -R 0777 /etc/logstash
    