server:
  port: 8080
insight-finder:
  # redirect url after authentication from identity provider
  serverUrl: https://app.insightfinder.com
  samlUrl: https://saml.insightfinder.com
  # saml application acts as service provider, it uses the following credentials to sign the request to teleport
  # generate: openssl req -newkey rsa:2048 -nodes -keyout local.key -x509 -days 365 -out local.crt
  sp-key: /app/saml_cert/local.key
  sp-cert: /app/saml_cert/local.crt

saml:
  idp:
    insightfinder:
      entity-id: entity-id-url
      # use firstname-key to extract first name info of the user from response of idp
      firstname-key: firstname-key
      lastname-key: lastname-key
      # use email-key to extract email info of the user from response of idp
      email-key: email-key
      singlesignon-url: singlesignon-url
      # certificate provided by idp
      idp-cert: /app/saml_cert/SAML-IDP-X509.pem