---
# defaults file for logstash-ansible
# These variables are using the logstash formatting for referencing the fields provided from filebeat.
# If the filebeat field that is being referenced needs to be updated, update these variables.
userName: "{{ username }}"
project_name: "%{[fields][site]}-%{[fields][technology]}-%{[fields][log]}-%{[fields][foundation]}" #
hostname: "%{[host][hostname]}"
component_name: "%{[fields][technology]}"
license_key: "{{ license_key }}"
server_url: "{{ server_url }}"
logstash_user: "{{ logstash_user }}"
ls_user: "{{ ls_user }}"
ls_group: "{{ ls_group }}"