apiVersion: v1
kind: ConfigMap
metadata:
  name: if-power-collector-config-json-cm
  namespace: {{ .Release.Namespace }}
data:
    {{- range $index, $configValue := .Values.powerCollectorAgent.config }}
    {{- if or (eq $configValue.type "powerFlex") (eq $configValue.type "powerScale") (eq $configValue.type "powerStore")}}
    {{$configValue.name}}.json: |-
        {
            "{{$configValue.metricEndpoint}}":[]
        }
    {{- end }}
    {{- end }}