apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: 1
  strategy:
        type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      imagePullSecrets:
      {{- range .Values.powerCollectorAgent.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      containers:
      - name: agent
        imagePullPolicy: Always
        image: {{ .Values.powerCollectorAgent.image }}
        tty: true
        env:
        - name: AGENT_RUN_INTERVAL
          value: {{ .Values.powerCollectorAgent.runInterval | quote }}
        volumeMounts:
        - name: config-ini-volume
          mountPath: /root/powerAgent/configMap-config-ini
        
        - name: config-json-volume
          mountPath: /root/powerAgent/configMap-config-json

        - name: certificate-volume
          mountPath: /etc/pki/ca-trust/source/anchors
      volumes:
      - name: config-ini-volume
        configMap:
          name: {{ .Release.Name }}-config-ini-cm
          items:
          {{- range $configValue := .Values.powerCollectorAgent.config }}
          - key: {{$configValue.name}}.ini
            path: {{$configValue.name}}.ini
          {{- end }}

      - name: config-json-volume
        configMap:
          name: {{ .Release.Name }}-config-json-cm
          items:
          {{- range $configValue := .Values.powerCollectorAgent.config }}
          {{- if or (eq $configValue.type "powerFlex") (eq $configValue.type "powerScale") (eq $configValue.type "powerStore")}}
          - key: {{$configValue.name}}.json
            path: {{$configValue.name}}.json
          {{- end }}
          {{- end }}
      
      - name: certificate-volume
        configMap:
          name: {{ .Release.Name }}-dell-root-ca-cert
          items:
          - key: cert.pem
            path: cert.pem