#fluentd-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "if-fluentd.fullname" . }}
  labels:
    app: if-fluentd
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: if-fluentd
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: if-fluentd
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: if-fluentd
      containers:
      - name: if-fluentd
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentconfig
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: if-plugin
          mountPath: /fluentd/plugins/fluent-plugin-out-InsightFinder.gemspec
          subPath: fluent-plugin-out-InsightFinder.gemspec
        - name: out-insightfinder
          mountPath: /fluentd/plugins/out_InsightFinder.rb
          subPath: out_InsightFinder.rb
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: if-plugin
        configMap:
          name: fluentd-configmap-if-plugin
      - name: out-insightfinder
        configMap:
          name: fluentd-configmap-out-insightfinder
      - name: fluentconfig
        configMap:
          name: fluentd-configmap-conf
