apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: if-event-push-agent
  labels:
    app: if-event-push-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: if-event-push-agent
  template:
    metadata:
      labels:
        app: if-event-push-agent
    spec:
      imagePullSecrets:
      {{- range .Values.eventPushAgent.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      containers:
      - name: agent
        imagePullPolicy: Always
        image: {{ .Values.eventPushAgent.image }}
        tty: true
          {{- if eq (len .Values.eventPushAgent.users) 0 }}
          {{- else }}
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app-root/src/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: if-event-push-agent-cm
          items:
          {{- range $index,$configValue := .Values.eventPushAgent.users}}
          - key: {{ $configValue.name }}.ini
            path: {{ $configValue.name }}.ini
          {{- end}}
          {{- end }}