# Default values for webhook-app.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: webhook-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  readOnlyRootFilesystem: true

config:
  insightfinder:
    url: "https://app.insightfinder.com"

schedule: "*/10 * * * *"
