# Agent Configuration
agent:
  name: "Rag File Uploader"
  version: "1.0"
  chunk_size: 10
  dir: "/home/tianren/Desktop/GAI-PGVector-Scripts/Microsoft_Documents"

api:
  GenAI_address: "http://localhost:8000"
  company: "_public"
  dataset: "Microsoft Documents"