agent:
  # Agent behavior settings
  log_level: INFO
  data_format: JSON
  timezone: UTC
  filters_include: ""
  filters_exclude: ""

cambium:
  # Cambium Network Configuration
  email: 
  password: 
  base_url: 
  login_url: https://cloud.cambiumnetworks.com/#/
  max_retries: 3
  worker_count: 30
  collection_interval_seconds: 60

insightfinder:
  # InsightFinder Platform Configuration
  server_url: https://app.insightfinder.com
  username: 
  license_key: 
  project_name: Cambium-Metrics
  system_name: Cambium Test
  project_type: Metric
  cloud_type: OnPremise
  instance_type: OnPremise
  is_container: false
  sampling_interval: 60

metric_filter:
  # Metric filtering configuration
  # Set to true to enable streaming of specific metrics to InsightFinder
  # Set to false to disable streaming (default: false for all metrics)
  
  # System metrics
  available_memory: false
  cpu_utilization: false
  
  # Radio metrics
  num_clients_5g: false
  channel_utilization_5g: false
  num_clients_6g: false
  channel_utilization_6g: false
  channel_utilization_5g_clients_over_35: true
  channel_utilization_6g_clients_over_35: true
  
  # Client-derived metrics (requires Wi-Fi devices with client data)
  rssi_avg: false
  snr_avg: false
  clients_rssi_below_74: false
  clients_rssi_below_78: false
  clients_rssi_below_80: false
  clients_snr_below_15: false
  clients_snr_below_18: false
  clients_snr_below_20: false

threshold:
  # Minimum client thresholds for percentage calculations
  # Calculate percentages only if client count is >= threshold, otherwise set to 0
  min_clients_rssi_threshold: 10  # Minimum clients required for RSSI percentage calculations
  min_clients_snr_threshold: 10   # Minimum clients required for SNR percentage calculations
