apiVersion: v1
kind: ConfigMap
metadata:
    name: config-cm
data:
    config.ini: |-
        [prometheus]
        ## prometheus info
        # required
        prometheus_uri = {{ .Values.prometheus.uri }}
        # Basic Authentication
        user = {{ .Values.prometheus.user }}
        password = {{ .Values.prometheus.password }}
        # True or False
        verify_certs = {{ .Values.prometheus.verify_certs }}
        # path to ca bundle
        ca_certs = {{ .Values.prometheus.ca_certs }}
        # path to client cert
        client_cert = {{ .Values.prometheus.client_cert }}
        # path to client key
        client_key = {{ .Values.prometheus.client_key }}

        ## metrics
        # Prometheus query used to query all the needed metrics. If not set, it will use `{__name__=~".+"}` to query all metrics.
        prometheus_query = {{ .Values.prometheus.prometheus_query }}
        # metric's name field, Multiple fields are separated by commas. EX: __name__, job, the metric name =  {__name__}_{job}
        metrics_name_field = {{ .Values.prometheus.metrics_name_field }}
        # history data time config. If these options is set, the agent will query results by time range
        # time range, Example: 2020-04-14 00:00:00,2020-04-15 00:00:00
        his_time_range = {{ .Values.prometheus.his_time_range }}

        # raw, rawtail, csv, csvtail, xls, xlsx, json, jsontail, avro, or xml
        # *tail formats keep track of the current file & position + completed files in [state] below
        data_format = {{ .Values.prometheus.data_format }}

        ## message parsing
        # timestamp format, as library [arrow]. multiple fields can be formatted together to create the timestamp a la `YYYY-MM-DD HH:mm:ss ZZ`. If multiple fields could contain the timestamp, a comma-delimited list may be entered (no value of which may use the aforementioned {formatting}), of which the first found will be selected (treating the list as a priority list). ex `timestamp1,timestamp2`
        timestamp_format = {{ .Values.prometheus.timestamp_format }}
        # timezone, as per pytz
        timezone = {{ .Values.prometheus.timezone }}
        timestamp_field = {{ .Values.prometheus.timestamp_field }}
        # Timezone of the timestamp data to be sent and stored in target DB (InsightFinder). Default is UTC. Only if you wish the data to be stored in other time zones in InsightFinder, this field should be specified to be the desired time zone.
        target_timestamp_timezone = {{ .Values.prometheus.target_timestamp_timezone }}
        component_field = {{ .Values.prometheus.component_field }}
        # if no instance given, will set to 'Application'. Can also set instance name from multiple fields which separated by commas. Ex: instance_name_part1,instance_name_part2.
        instance_field = {{ .Values.prometheus.instance_field }}
        # instance_whitelist is a regex string used to define which instances will be filtered.
        instance_whitelist = {{ .Values.prometheus.instance_whitelist }}
        # Field name of device. Can also set device name from multiple fields which separated by commas. Ex: device_name_part1,device_name_part2.
        device_field = {{ .Values.prometheus.device_field }}
        # The connector for build `instance_field` or `device_field` from multiple fields. Default is `-`.
        instance_connector = {{ .Values.prometheus.instance_connector }}
        # number of thread to used in the pool, default is 20
        thread_pool = {{ .Values.prometheus.thread_pool }}
        # number of the worker processes, default is count_of_cpu * 4
        processes = {{ .Values.prometheus.processes }}
        # minutes the main process wait for workers to finish, default is 5
        timeout = {{ .Values.prometheus.timeout }}

        ## proxy
        agent_http_proxy = {{ .Values.prometheus.agent_http_proxy }}
        agent_https_proxy = {{ .Values.prometheus.agent_https_proxy }}

        [insightfinder]
        user_name = {{ .Values.insightfinder.user_name }}
        license_key = {{ .Values.insightfinder.license_key }}
        token = {{ .Values.insightfinder.token }}
        # Name of the project created in the InsightFinder UI, If this project is not exist, agent will create it automatically.
        project_name = {{ .Values.insightfinder.project_name }}
        # Name of system owned by project. If project_name is not exist in InsightFinder, agent will create a new system automatically from this field or project_name.
        system_name = {{ .Values.insightfinder.system_name }}
        # metric, metricreplay, log, logreplay, alert, alertreplay, incident, incidentreplay, deployment, deploymentreplay, trace, tracereplay
        project_type = {{ .Values.insightfinder.project_type }}
        # Set to `YES` if project is container.
        containerize = {{ .Values.insightfinder.containerize }}
        sampling_interval = {{ .Values.insightfinder.sampling_interval }}
        run_interval = {{ .Values.insightfinder.run_interval }}
        # what size to limit chunks sent to IF to, as kb
        chunk_size_kb = {{ .Values.insightfinder.chunk_size_kb }}
        if_url = {{ .Values.insightfinder.if_url }}
        if_http_proxy = {{ .Values.insightfinder.if_http_proxy }}
        if_https_proxy = {{ .Values.insightfinder.if_http_proxy }}
