name: Publish Tarball Packages
run-name: Running on ${{ github.ref }}
on:
  push:
    # paths:
    #   - 'prometheus/**'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true

      - name: List all changed files
        run: |
          echo ${{toJson(steps.changed-files.outputs.all_changed_files)}}

  # release:
  #   runs-on: ubuntu-latest
  #   needs: changed_files
  #   strategy:
  #     matrix: ${{fromJson(needs.changed_files.outputs.all_changed_files)}}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Create tarball
  #       run: tar zcf prometheus-$(date +%Y%m%d%H%M).tgz prometheus
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: prometheus.tgz
  #         tag_name: prometheus