name: Publish Tarball Packages
run-name: Running on ${{ github.ref }}
on:
  push:
    paths:
      - 'logFileReplay/**'
      - 'prometheus/**'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  release:
    needs: changed_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.changed_files.outputs.dirs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create tarball
        run: tar zcf ${{ matrix.dir }}-$(date +%Y%m%d%H%M).tgz ${{ matrix.dir }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.dir }}-*.tgz
          tag_name: ${{ matrix.dir }}