name: Publish Tarball Packages
run-name: Running on ${{ github.ref }}
on:
  push:
    paths:
      - 'prometheus/**'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Create tarball
  #       run: tar zcf prometheus-$(date +%Y%m%d%H%M).tgz prometheus
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: prometheus.tgz
  #         tag_name: prometheus